//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public int id { get; set; }
        public int HD_id { get; set; }
        public int SP_id { get; set; }
        public int DonGiaBan { get; set; }
        public int SoLuong { get; set; }
    
        public virtual BangHoaDon BangHoaDon { get; set; }
        public virtual BangSanPham BangSanPham { get; set; }
    }
}
